### PR TITLE
udev: import previous results of blkid when in suspended state

### PR DESCRIPTION
**Pull request by yuwata**
Follow-up for e10f67e91728f1e576803df884049ecbd92874d0.

The commit e10f67e91728f1e576803df884049ecbd92874d0 tries to keep device node symlinks even if the device is in the suspended state. However, necessary properties that may previously obtained by the blkid command were not imported at least in the .rules file. So, unless ID_FS_xyz properties are imported by another earlier .rules file, the device node symlinks are still lost when event is processed in the suspended state.

Let's explicitly import the necessary properties.

C.f. https://bugzilla.redhat.com/show_bug.cgi?id=2158628

### CODE REVIEW

**Comment by prajnoha** [comment]
There was a discussion around this change at that time: https://lore.kernel.org/all/5eda612b861cf911319087c4c5af8bb6815e1928.camel@suse.com/

I even proposed to import all the blkid values directly in 13-dm-disk.rules in that discussion, but in the end, we decided to do that only for multipath devices specifically (hence the imports are in 11-dm-mpath.rules). The reason was simply to lower the risk of unexpected regressions to occur, because we had bad experience before with changing the rules and various side-effects it may bring (...because those rules to handle DM and its various subsystems are quire complex).

I'm not quite sure right now why there's such an event while a DM device is suspende.  I'll check and see...

**Comment by prajnoha** [comment]
(copying the text from [the RH bugzilla report](https://bugzilla.redhat.com/show_bug.cgi?id=2158628):

The issue here is that there are two uevents generated with a race. From my test, I can see (the dm-6 is the top level thin LV):

 KERNEL\[1632.888585\] change   /devices/virtual/block/dm-6 (block)  
 ACTION=change  
 DEVPATH=/devices/virtual/block/dm-6  
 SUBSYSTEM=block  
 RESIZE=1  
 DEVNAME=/dev/dm-6  
 DEVTYPE=disk  
 DISKSEQ=26  
 SEQNUM=2942  
 MAJOR=253  
 MINOR=6

 KERNEL\[1632.889364\] change   /devices/virtual/block/dm-6 (block)  
 ACTION=change  
 DEVPATH=/devices/virtual/block/dm-6  
 SUBSYSTEM=block  
 DM\_COOKIE=6333296  
 DEVNAME=/dev/dm-6  
 DEVTYPE=disk  
 DISKSEQ=26  
 SEQNUM=2943  
 MAJOR=253  
 MINOR=6

  
The first uevent is generated to notify about the change in size (it contains RESIZE="1"). This is relatively new in kernel: torvalds/linux@e598a72

The second uevent notifies about the DM device being resumed, that is, flipping DM device state from "suspended" to "active".

While the first uevent is being processed by udev, the DM device doesn't need to be resumed yet and so we may see the device as suspended. This causes blkid scan to be skipped and so the appropriate ID\_FS\_\* variables are not set. As described earlier somewhere in this thread (or the github PR from comment #20), this causes systemd to unmount the mount point for which we lose the appropriate identification.

To fix this, we either need to reorder the uevents so that the "resize" one goes after "DM resume" one - that would be probably more correct solution to this. Or, alternatively, we make the udev rules to simply count with this situation (which is basically what is proposed in PR from comment #20). Since it's easier to change userspace and we need to fix this quickly, we will change the udev rules.

**Comment by prajnoha** [comment]
Patch applied, thanks!
https://sourceware.org/git/?p=lvm2.git;a=commit;h=94f77a4d8d9737fca05fb4e451678ec440c68670

**Comment by yuwata** [comment]
Sorry for late response. And thank you for your quick consideration of this PR!

**Pull request closed without merging**
